#!/bin/bash
# Copyright 2010 Curtis McEnroe <programble@gmail.com>
#
# This file is part of BSH.
#
# BSH is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BSH is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with BSH.  If not, see <http://www.gnu.org/licenses/>.

# Defaults
CC=clang

# Load previous config if it exists
if [ -f build/config ]; then
    . build/config
fi

# Clear previous config
echo "# Configuration generated by config.sh" > build/config
echo "/* Configuration generated by config.sh */" > build/config.h

function conf
{
    echo -n "$3: [$2] "
    read CONF
    if [ ! "$CONF" ]; then
        CONF=$2
    fi
    echo "$1=$CONF" >> build/config
    echo "#define $1 $CONF" >> build/config.h
}

function ynconf
{
    if [[ "$2" == "y" ]]; then
        echo -n "$3? [Y/n] "
    else
        echo -n "$3? [y/N] "
    fi
    read YNCONF
    if [ ! "$YNCONF" ]; then
        YNCONF=$2
    fi
    if [[ "$YNCONF" == "y" ]]; then
        echo "$1=$YNCONF" >> build/config
        echo "#define $1" >> build/config.sh
    fi
}

conf CC $CC "C Compiler"
